<?php

use Illuminate\Database\Seeder;

class FighterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $list = [
                    'F' => [
                        'STRAWWEIGHT' => [
                            ['name' => 'JESSICA ANDRADE', 'style' => 'BALANCED', 'cartel' => '20-8-0'],
                            ['name' => 'JOANNE CALDERWOOD', 'style' => 'BALANCED', 'cartel' => '14-5'],
                            ['name' => 'CYNTHIA CALVILLO', 'style' => 'WRESTLER', 'cartel' => '9-1-1'],
                            ['name' => 'MACKENZIE DERN', 'style' => 'JIU-JITSU', 'cartel' => '8-1'],
                            ['name' => 'CARLA ESPARZA', 'style' => 'WRESTLER', 'cartel' => '17-6'],
                            ['name' => 'CLAUDIA GADELHA', 'style' => 'JIU-JITSU', 'cartel' => '18-4'],
                            ['name' => 'ALEXA GRASSO', 'style' => 'BOXER', 'cartel' => '11-3'],
                            ['name' => 'FELICE HERRIG', 'style' => 'BOXER', 'cartel' => '14-9'],
                            ['name' => 'ANGELA HILL', 'style' => 'BALANCED', 'cartel' => '12-8'],
                            ['name' => 'JOANNA JEDRZEJCZYK', 'style' => 'KICKBOXER', 'cartel' => '16-4'],
                            ['name' => 'KAROLINA KOWALKIEWICZ', 'style' => 'BALANCED', 'cartel' => '12-6'],
                            ['name' => 'RANDA MARKOS', 'style' => 'WRESTLER', 'cartel' => '10-8-1'],
                            ['name' => 'MARYNA MOROZ', 'style' => 'BOXER', 'cartel' => '10-3'],
                            ['name' => 'ROSE NAMAJUNAS', 'style' => 'JIU-JITSU', 'cartel' => '9-4'],
                            ['name' => 'JESSICA PENNE', 'style' => 'JIU-JITSU', 'cartel' => '12-5'],
                            ['name' => 'TATIANA SUAREZ', 'style' => 'WRESTLER', 'cartel' => '8-0'],
                            ['name' => 'TECIA TORRES', 'style' => 'KICKBOXER', 'cartel' => '11-5'],
                            ['name' => 'PAIGE VANZANT', 'style' => 'KICKBOXER', 'cartel' => '8-5'],
                            ['name' => 'MICHELLE WATERSON', 'style' => 'KICKBOXER', 'cartel' => '17-8'],
                            ['name' => 'WEILI ZHANG', 'style' => 'BALANCED', 'cartel' => '21-1'],
                        ],
                        'FLYWEIGHT' => [
                            ['name' => 'JOANNE CALDERWOOD', 'style' => 'BALANCED', 'cartel' => '14-5'],
                            ['name' => 'CYNTHIA CALVILLO', 'style' => 'WRESTLER', 'cartel' => '9-1-1'],
                            ['name' => 'KATLYN CHOOKAGIAN', 'style' => 'BOXER', 'cartel' => '14-3'],
                            ['name' => 'ALEXIS DAVIS', 'style' => 'JIU-JITSU', 'cartel' => '19-10'],
                            ['name' => 'ASHLEE EVANS-SMITH', 'style' => 'BOXER', 'cartel' => '6-4'],
                            ['name' => 'JESSICA EYE', 'style' => 'BOXER', 'cartel' => '15-8-1'],
                            ['name' => 'ALEXA GRASSO', 'style' => 'BOXER', 'cartel' => '11-3'],
                            ['name' => 'JOANNA JEDRZEJCZYK', 'style' => 'KICKBOXER', 'cartel' => '16-4'],
                            ['name' => 'MARYNA MOROZ', 'style' => 'BOXER', 'cartel' => '10-3'],
                            ['name' => 'LAUREN MURPHY', 'style' => 'WRESTLER', 'cartel' => '13-4'],
                            ['name' => 'VALENTINA SHEVCHENKO', 'style' => 'BALANCED', 'cartel' => '19-3'],
                            ['name' => 'PAIGE VANZANT', 'style' => 'KICKBOXER', 'cartel' => '8-5'],
                        ],
                        'BANTAMWEIGHT' => [
                            ['name' => 'BETHE CORREIA', 'style' => 'BOXER', 'cartel' => '11-5-1'],
                            ['name' => 'CRIS CYBORG', 'style' => 'KICKBOXER', 'cartel' => '22-2-1'],
                            ['name' => 'ALEXIS DAVIS', 'style' => 'JIU-JITSU', 'cartel' => '19-10'],
                            ['name' => 'GERMAINE DE RANDAMIE', 'style' => 'KICKBOXER', 'cartel' => '9-4'],
                            ['name' => 'ASHLEE EVANS-SMITH', 'style' => 'BOXER', 'cartel' => '6-4'],
                            ['name' => 'JESSICA EYE', 'style' => 'BOXER', 'cartel' => '15-8-1'],
                            ['name' => 'HOLLY HOLM', 'style' => 'KICKBOXER', 'cartel' => '13-5'],
                            ['name' => 'ASPEN LADD', 'style' => 'BALANCED', 'cartel' => '9-1'],
                            ['name' => 'SARA MCMANN', 'style' => 'WRESTLER', 'cartel' => '12-5'],
                            ['name' => 'LAUREN MURPHY', 'style' => 'WRESTLER', 'cartel' => '13-4'],
                            ['name' => 'AMANDA NUNES', 'style' => 'KICKBOXER', 'cartel' => '20-4'],
                            ['name' => 'RAQUEL PENNINGTON', 'style' => 'BOXER', 'cartel' => '11-8'],
                            ['name' => 'JULIANNA PEÑA', 'style' => 'JIU-JITSU', 'cartel' => '9-3'],
                            ['name' => 'MARION RENEAU', 'style' => 'WRESTLER', 'cartel' => '9-6-1'],
                            ['name' => 'RONDA ROUSEY', 'style' => 'JIU-JITSU', 'cartel' => '12-2'],
                            ['name' => 'VALENTINA SHEVCHENKO', 'style' => 'BALANCED', 'cartel' => '19-3'],
                            ['name' => 'MIESHA TATE', 'style' => 'WRESTLER', 'cartel' => '18-7'],
                            ['name' => 'KETLEN VIEIRA', 'style' => 'BALANCED', 'cartel' => '10-1'],
                        ]
                    ],
                    'M' => [
                        'FLYWEIGHT' => [
                            ['name' => 'JOSEPH BENAVIDEZ', 'style' => 'WRESTLER', 'cartel' => '28-7'],
                            ['name' => 'RAY BORG', 'style' => 'BALANCED', 'cartel' => '13-5'],
                            ['name' => 'HENRY CEJUDO', 'style' => 'WRESTLER', 'cartel' => '16-2'],
                            ['name' => 'TJ DILLASHAW', 'style' => 'BALANCED', 'cartel' => '16-4'],
                            ['name' => 'JOHN DODSON', 'style' => 'KICKBOXER', 'cartel' => '21-12'],
                            ['name' => 'TIM ELLIOTT', 'style' => 'JIU-JITSU', 'cartel' => '16-11-1'],
                            ['name' => 'DEIVESON FIGUEIREDO', 'style' => 'BALANCED', 'cartel' => '19-1'],
                            ['name' => 'JUSSIER FORMIGA', 'style' => 'JIU-JITSU', 'cartel' => '23-8'],
                            ['name' => 'DEMETRIOUS JOHNSON', 'style' => 'BALANCED', 'cartel' => '30-3-1'],
                            ['name' => 'BRANDON MORENO', 'style' => 'WRESTLER', 'cartel' => '17-5-1'],
                            ['name' => 'ALEXANDRE PANTOJA', 'style' => 'BALANCED', 'cartel' => '22-5'],
                            ['name' => 'LOUIS SMOLKA', 'style' => 'KICKBOXER', 'cartel' => '16-7'],
                        ],
                        'BANTAMWEIGHT' => [
                            ['name' => 'IURI ALCANTARA', 'style' => 'KICKBOXER', 'cartel' => '35-10-1'],
                            ['name' => 'JOSE ALDO', 'style' => 'KICKBOXER', 'cartel' => '28-7'],
                            ['name' => 'THOMAS ALMEIDA', 'style' => 'BALANCED', 'cartel' => '21-3'],
                            ['name' => 'RAPHAEL ASSUNCAO', 'style' => 'JIU-JITSU', 'cartel' => '27-8'],
                            ['name' => 'RENAN BARAO', 'style' => 'KICKBOXER', 'cartel' => '34-9-1'],
                            ['name' => 'RAY BORG', 'style' => 'BALANCED', 'cartel' => '13-5'],
                            ['name' => 'HENRY CEJUDO', 'style' => 'WRESTLER', 'cartel' => '16-2'],
                            ['name' => 'DOMINICK CRUZ', 'style' => 'BALANCED', 'cartel' => '22-3'],
                            ['name' => 'TJ DILLASHAW', 'style' => 'BALANCED', 'cartel' => '16-4'],
                            ['name' => 'JOHN DODSON', 'style' => 'KICKBOXER', 'cartel' => '21-12'],
                            ['name' => 'JOHNNY EDUARDO', 'style' => 'BOXER', 'cartel' => '28-12'],
                            ['name' => 'TIM ELLIOTT', 'style' => 'JIU-JITSU', 'cartel' => '16-11-1'],
                            ['name' => 'URIJAH FABER', 'style' => 'WRESTLER', 'cartel' => '35-11'],
                            ['name' => 'CODY GARBRANDT', 'style' => 'BOXER', 'cartel' => '12-3'],
                            ['name' => 'JOHN LINEKER', 'style' => 'KICKBOXER', 'cartel' => '32-9'],
                            ['name' => 'MARLON MORAES', 'style' => 'KICKBOXER', 'cartel' => '23-6-1'],
                            ['name' => 'SEAN OMALLEY', 'style' => 'KICKBOXER', 'cartel' => '12-1'],
                            ['name' => 'JIMMIE RIVERA', 'style' => 'WRESTLER', 'cartel' => '23-4'],
                            ['name' => 'FRANKIE SAENZ', 'style' => 'WRESTLER', 'cartel' => '12-7'],
                            ['name' => 'CORY SANDHAGEN', 'style' => 'KICKBOXER', 'cartel' => '12-2'],
                            ['name' => 'LOUIS SMOLKA', 'style' => 'KICKBOXER', 'cartel' => '16-7'],
                            ['name' => 'ALJAMAIN STERLING', 'style' => 'WRESTLER', 'cartel' => '19-3'],
                            ['name' => 'EDDIE WINELAND', 'style' => 'KICKBOXER', 'cartel' => '24-14-1'],
                            ['name' => 'SON YADONG', 'style' => 'BOXER', 'cartel' => '16-4-2'],
                            ['name' => 'PETR YAN', 'style' => 'BALANCED', 'cartel' => '15-1'],
                        ],
                        'FEATHERWEIGHT' => [
                            ['name' => 'JOSE ALDO', 'style' => 'KICKBOXER', 'cartel' => '28-7'],
                            ['name' => 'ARNOLD ALLEN', 'style' => 'KICKBOXER', 'cartel' => '16-1'],
                            ['name' => 'MAKWAN AMIRKHANI', 'style' => 'WRESTLER', 'cartel' => '16-4'],
                            ['name' => 'RAPHAEL ASSUNCAO', 'style' => 'JIU-JITSU', 'cartel' => '27-8'],
                            ['name' => 'EDSON BARBOZA', 'style' => 'KICKBOXER', 'cartel' => '20-9'],
                            ['name' => 'MIRSAD BEKTIC', 'style' => 'BOXER', 'cartel' => '13-3'],
                            ['name' => 'ALEX CACERES', 'style' => 'KICKBOXER', 'cartel' => '16-12-1'],
                            ['name' => 'DOO HO CHOI', 'style' => 'BOXER', 'cartel' => '14-4'],
                            ['name' => 'FRANKIE EDGAR', 'style' => 'WRESTLER', 'cartel' => '24-8-1'],
                            ['name' => 'DARREN ELKINS', 'style' => 'BOXER', 'cartel' => '24-9'],
                            ['name' => 'JOSH EMMETT', 'style' => 'WRESTLER', 'cartel' => '16-2'],
                            ['name' => 'URIJAH FABER', 'style' => 'WRESTLER', 'cartel' => '35-11'],
                            ['name' => 'CLAY GUIDA', 'style' => 'WRESTLER', 'cartel' => '35-20'],
                            ['name' => 'MAX HOLLOWAY', 'style' => 'KICKBOXER', 'cartel' => '21-6'],
                            ['name' => 'DANIEL HOOKER', 'style' => 'BOXER', 'cartel' => '20-9'],
                            ['name' => 'MICHAEL JOHNSON', 'style' => 'WRESTLER', 'cartel' => '19-16'],
                            ['name' => 'CHAN SUNG JUNG', 'style' => 'KICKBOXER', 'cartel' => '16-5'],
                            ['name' => 'RICARDO LAMAS', 'style' => 'KICKBOXER', 'cartel' => '19-8'],
                            ['name' => 'ZABIT MAGOMEDSHARIPOV', 'style' => 'KICKBOXER', 'cartel' => '18-1'],
                            ['name' => 'CONOR MCGREGOR', 'style' => 'KICKBOXER', 'cartel' => '22-4'],
                            ['name' => 'RENATO MOICANO', 'style' => 'JIU-JITSU', 'cartel' => '14-3-1'],
                            ['name' => 'CHARLES OLIVEIRA', 'style' => 'JIU-JITSU', 'cartel' => '29-8-1'],
                            ['name' => 'BRIAN ORTEGA', 'style' => 'JIU-JITSU', 'cartel' => '14-1-1'],
                            ['name' => 'ANTHONY PETTIS', 'style' => 'KICKBOXER', 'cartel' => '23-10'],
                            ['name' => 'DUSTIN POIRIER', 'style' => 'KICKBOXER', 'cartel' => '26-6-1'],
                            ['name' => 'YAIR RODRIGUEZ', 'style' => 'KICKBOXER', 'cartel' => '13-2-1'],
                            ['name' => 'CHARLES ROSA', 'style' => 'JIU-JITSU', 'cartel' => '13-4'],
                            ['name' => 'DIEGO SANCHEZ', 'style' => 'BOXER', 'cartel' => '30-12'],
                            ['name' => 'JEREMY STEPHENS', 'style' => 'BOXER', 'cartel' => '28-18-1'],
                            ['name' => 'CUB SWANSON', 'style' => 'KICKBOXER', 'cartel' => '26-11'],
                            ['name' => 'ALEXANDER VOLKANOVSKI', 'style' => 'BALANCED', 'cartel' => '22-1'],
                        ],
                        'LIGHTWEIGHT' => [
                            ['name' => 'EDDIE ALVAREZ', 'style' => 'KICKBOXER', 'cartel' => '30-7-1'],
                            ['name' => 'EDSON BARBOZA', 'style' => 'KICKBOXER', 'cartel' => '20-9'],
                            ['name' => 'GILBERT BURNS', 'style' => 'BOXER', 'cartel' => '19-3'],
                            ['name' => 'DONALD CERRONE', 'style' => 'KICKBOXER', 'cartel' => '36-15-1'],
                            ['name' => 'MICHAEL CHIESA', 'style' => 'WRESTLER', 'cartel' => '17-4'],
                            ['name' => 'BENEIL DARIUSH', 'style' => 'JIU-JITSU', 'cartel' => '19-4-1'],
                            ['name' => 'MARC DIAKIESE', 'style' => 'KICKBOXER', 'cartel' => '14-4'],
                            ['name' => 'NATE DIAZ', 'style' => 'BALANCED', 'cartel' => '20-12'],
                            ['name' => 'RAFAEL DOS ANJOS', 'style' => 'JIU-JITSU', 'cartel' => '29-13'],
                            ['name' => 'JOE DUFFY', 'style' => 'WRESTLER', 'cartel' => '16-5'],
                            ['name' => 'EVAN DUNHAM', 'style' => 'JIU-JITSU', 'cartel' => '18-9-1'],
                            ['name' => 'FRANKIE EDGAR', 'style' => 'WRESTLER', 'cartel' => '24-8-1'],
                            ['name' => 'JOSH EMMETT', 'style' => 'WRESTLER', 'cartel' => '16-2'],
                            ['name' => 'PAUL FELDER', 'style' => 'KICKBOXER', 'cartel' => '17-5'],
                            ['name' => 'TONY FERGUSON', 'style' => 'BOXER', 'cartel' => '25-4'],
                            ['name' => 'JUSTIN GAETHJE', 'style' => 'KICKBOXER', 'cartel' => '22-2'],
                            ['name' => 'BOBBY GREEN', 'style' => 'BOXER', 'cartel' => '26-10-1'],
                            ['name' => 'CLAY GUIDA', 'style' => 'WRESTLER', 'cartel' => '35-20'],
                            ['name' => 'ALEXANDER HERNANDEZ', 'style' => 'WRESTLER', 'cartel' => '11-3'],
                            ['name' => 'MAX HOLLOWAY', 'style' => 'KICKBOXER', 'cartel' => '21-6'],
                            ['name' => 'DANIEL HOOKER', 'style' => 'BOXER', 'cartel' => '20-9'],
                            ['name' => 'AL IAQUINTA', 'style' => 'BOXER', 'cartel' => '14-6-1'],
                            ['name' => 'MICHAEL JOHNSON', 'style' => 'WRESTLER', 'cartel' => '19-16'],
                            ['name' => 'RUSTAM KHABILOV', 'style' => 'WRESTLER', 'cartel' => '24-4'],
                            ['name' => 'JOE LAUZON', 'style' => 'JIU-JITSU', 'cartel' => '28-15'],
                            ['name' => 'KEVIN LEE', 'style' => 'WRESTLER', 'cartel' => '18-6'],
                            ['name' => 'NIK LENTZ', 'style' => 'WRESTLER', 'cartel' => '30-11-2-1'],
                            ['name' => 'JORGE MASVIDAL', 'style' => 'BOXER', 'cartel' => '35-14'],
                            ['name' => 'JAKE MATTHEWS', 'style' => 'KICKBOXER', 'cartel' => '16-4'],
                            ['name' => 'CONOR MCGREGOR', 'style' => 'KICKBOXER', 'cartel' => '22-4'],
                            ['name' => 'YANCY MEDEIROS', 'style' => 'KICKBOXER', 'cartel' => '15-7-0-1'],
                            ['name' => 'JIM MILLER', 'style' => 'JIU-JITSU', 'cartel' => '23-15-0-1'],
                            ['name' => 'RENATO MOICANO', 'style' => 'JIU-JITSU', 'cartel' => '14-3-1'],
                            ['name' => 'KHABIB NURMAGOMEDOV', 'style' => 'WRESTLER', 'cartel' => '28-0'],
                            ['name' => 'ALEX OLIVEIRA', 'style' => 'KICKBOXER', 'cartel' => '28-8-1-2'],
                            ['name' => 'CHARLES OLIVEIRA', 'style' => 'JIU-JITSU', 'cartel' => '29-8-0-1'],
                            ['name' => 'BJ PENN', 'style' => 'JIU-JITSU', 'cartel' => '16-14-2'],
                            ['name' => 'ANTHONY PETTIS', 'style' => 'KICKBOXER', 'cartel' => '23-10'],
                            ['name' => 'DUSTIN POIRIER', 'style' => 'KICKBOXER', 'cartel' => '26-6-0-1'],
                            ['name' => 'DIEGO SANCHEZ', 'style' => 'BOXER', 'cartel' => '30-12'],
                            ['name' => 'LEONARDO SANTOS', 'style' => 'JIU-JITSU', 'cartel' => '18-3-1'],
                            ['name' => 'JEREMY STEPHENS', 'style' => 'BOXER', 'cartel' => '28-18-0-1'],
                            ['name' => 'JAMES VICK', 'style' => 'BOXER', 'cartel' => '13-5'],
                            ['name' => 'ALEXANDER VOLKANOVSKI', 'style' => 'BALANCED', 'cartel' => '22-1'],
                        ],
                        'WELTERWEIGHT' => [
                            ['name' => 'OMARI AKHMEDOV', 'style' => 'BOXER', 'cartel' => '20-5-1'],
                            ['name' => 'BEN ASKREN', 'style' => 'WRESTLER', 'cartel' => '19-2-0-1'],
                            ['name' => 'TOM BREESE', 'style' => 'BOXER', 'cartel' => '11-2'],
                            ['name' => 'MATT BROWN', 'style' => 'KICKBOXER', 'cartel' => '22-17'],
                            ['name' => 'GILBERT BURNS', 'style' => 'BOXER', 'cartel' => '19-3'],
                            ['name' => 'DONALD CERRONE', 'style' => 'KICKBOXER', 'cartel' => '36-15-0-1'],
                            ['name' => 'MICHAEL CHIESA', 'style' => 'WRESTLER', 'cartel' => '17-4'],
                            ['name' => 'CARLOS CONDIT', 'style' => 'KICKBOXER', 'cartel' => '30-13'],
                            ['name' => 'COLBY COVINGTON', 'style' => 'WRESTLER', 'cartel' => '15-2'],
                            ['name' => 'NATE DIAZ', 'style' => 'BALANCED', 'cartel' => '20-12'],
                            ['name' => 'NICK DIAZ', 'style' => 'BOXER', 'cartel' => '26-9-0-2'],
                            ['name' => 'RAFAEL DOS ANJOS', 'style' => 'JIU-JITSU', 'cartel' => '29-13'],
                            ['name' => 'LEON EDWARDS', 'style' => 'KICKBOXER', 'cartel' => '18-3'],
                            ['name' => 'PAUL FELDER', 'style' => 'KICKBOXER', 'cartel' => '17-5'],
                            ['name' => 'TONY FERGUSON', 'style' => 'BOXER', 'cartel' => '25-4'],
                            ['name' => 'MICKEY GALL', 'style' => 'JIU-JITSU', 'cartel' => '6-3'],
                            ['name' => 'KELVIN GASTELUM', 'style' => 'WRESTLER', 'cartel' => '15-6-0-1'],
                            ['name' => 'ROYCE GRACIE', 'style' => 'JIU-JITSU', 'cartel' => '15-2-3'],
                            ['name' => 'JOHNY HENDRICKS', 'style' => 'WRESTLER', 'cartel' => '18-8'],
                            ['name' => 'MATT HUGHES', 'style' => 'WRESTLER', 'cartel' => '45-9'],
                            ['name' => 'ALAN JOUBAN', 'style' => 'KICKBOXER', 'cartel' => '16-7'],
                            ['name' => 'ROBBIE LAWLER', 'style' => 'BOXER', 'cartel' => '28-14-0-1'],
                            ['name' => 'KEVIN LEE', 'style' => 'WRESTLER', 'cartel' => '18-6'],
                            ['name' => 'NEIL MAGNY', 'style' => 'JIU-JITSU', 'cartel' => '23-7'],
                            ['name' => 'DEMIAN MAIA', 'style' => 'JIU-JITSU', 'cartel' => '28-10'],
                            ['name' => 'JORGE MASVIDAL', 'style' => 'BOXER', 'cartel' => '35-14'],
                            ['name' => 'JAKE MATTHEWS', 'style' => 'KICKBOXER', 'cartel' => '16-4'],
                            ['name' => 'CONOR MCGREGOR', 'style' => 'KICKBOXER', 'cartel' => '22-4'],
                            ['name' => 'TIM MEANS', 'style' => 'BOXER', 'cartel' => '30-12-1-1'],
                            ['name' => 'YANCY MEDEIROS', 'style' => 'KICKBOXER', 'cartel' => '15-7-0-1'],
                            ['name' => 'GUNNAR NELSON', 'style' => 'JIU-JITSU', 'cartel' => '17-5-1'],
                            ['name' => 'ALEX OLIVEIRA', 'style' => 'KICKBOXER', 'cartel' => '22-8-1-2'],
                            ['name' => 'BJ PENN', 'style' => 'JIU-JITSU', 'cartel' => '16-14-2'],
                            ['name' => 'MIKE PERRY', 'style' => 'BOXER', 'cartel' => '14-6'],
                            ['name' => 'ANTHONY PETTIS', 'style' => 'KICKBOXER', 'cartel' => '23-10'],
                            ['name' => 'SANTIAGO PONZINIBBIO', 'style' => 'KICKBOXER', 'cartel' => '27-3'],
                            ['name' => 'CM PUNK', 'style' => 'WRESTLER', 'cartel' => '0-2'],
                            ['name' => 'DIEGO SANCHEZ', 'style' => 'BOXER', 'cartel' => '30-12'],
                            ['name' => 'ERICK SILVA', 'style' => 'JIU-JITSU', 'cartel' => '20-11-0-1'],
                            ['name' => 'GEORGES ST-PIERRE', 'style' => 'BALANCED', 'cartel' => '26-2'],
                            ['name' => 'STEPHEN THOMPSON', 'style' => 'KICKBOXER', 'cartel' => '15-4-1'],
                            ['name' => 'DARREN TILL', 'style' => 'KICKBOXER', 'cartel' => '18-3-1'],
                            ['name' => 'KAMARU USMAN', 'style' => 'WRESTLER', 'cartel' => '17-1'],
                            ['name' => 'JAMES VICK', 'style' => 'BOXER', 'cartel' => '13-5'],
                            ['name' => 'TYRON WOODLEY', 'style' => 'WRESTLER', 'cartel' => '19-5-1'],
                        ],
                        'MIDDLEWEIGHT' => [
                            ['name' => 'ISRAEL ADESANYA', 'style' => 'KICKBOXER', 'cartel' => '19-0'],
                            ['name' => 'SAM ALVEY', 'style' => 'BOXER', 'cartel' => '33-14-0-1'],
                            ['name' => 'VITOR BELFORT', 'style' => 'KICKBOXER', 'cartel' => '26-14-0-1'],
                            ['name' => 'MICHAEL BISPING', 'style' => 'KICKBOXER', 'cartel' => '30-9'],
                            ['name' => 'TOM BRESSE', 'style' => 'BOXER', 'cartel' => '11-2'],
                            ['name' => 'DEREK BRUNSON', 'style' => 'WRESTLER', 'cartel' => '21-7'],
                            ['name' => 'JARED CANNONIER', 'style' => 'KICKBOXER', 'cartel' => '13-4'],
                            ['name' => 'PAULO COSTA', 'style' => 'KICKBOXER', 'cartel' => '13-0'],
                            ['name' => 'NICK DIAZ', 'style' => 'BOXER', 'cartel' => '26-9-0-2'],
                            ['name' => 'KELVIN GASTELUM', 'style' => 'WRESTLER', 'cartel' => '15-6-0-1'],
                            ['name' => 'ROYCE GRACIE', 'style' => 'JIU-JITSU', 'cartel' => '15-2-3'],
                            ['name' => 'URIAH HALL', 'style' => 'KICKBOXER', 'cartel' => '15-9'],
                            ['name' => 'DAN HENDERSON', 'style' => 'BOXER', 'cartel' => '32-15'],
                            ['name' => 'JACK HERMANSSON', 'style' => 'KICKBOXER', 'cartel' => '21-5'],
                            ['name' => 'KRZYSZTOF JOTKO', 'style' => 'KICKBOXER', 'cartel' => '22-4'],
                            ['name' => 'ROBBIE LAWLER', 'style' => 'BOXER', 'cartel' => '28-14-0-1'],
                            ['name' => 'LYOTO MACHIDA', 'style' => 'KICKBOXER', 'cartel' => '26-9'],
                            ['name' => 'DEMIAN MAIA', 'style' => 'JIU-JITSU', 'cartel' => '28-10'],
                            ['name' => 'LUKE ROCKHOLD', 'style' => 'KICKBOXER', 'cartel' => '16-5'],
                            ['name' => 'YOEL ROMERO', 'style' => 'WRESTLER', 'cartel' => '13-5'],
                            ['name' => 'THIAGO SANTOS', 'style' => 'KICKBOXER', 'cartel' => '21-7'],
                            ['name' => 'EDMEN SHAHBAZYAN', 'style' => 'KICKBOXER', 'cartel' => '11-1'],
                            ['name' => 'ANDERSON SILVA', 'style' => 'KICKBOXER', 'cartel' => '34-10'],
                            ['name' => 'WANDERLEI SILVA', 'style' => 'BOXER', 'cartel' => '35-14-1-1'],
                            ['name' => 'ANTHONY SMITH', 'style' => 'WRESTLER', 'cartel' => '33-15'],
                            ['name' => 'CHAEL SONNEN', 'style' => 'WRESTLER', 'cartel' => '31-17-1'],
                            ['name' => 'JACARE SOUZA', 'style' => 'JIU-JITSU', 'cartel' => '26-8-0-1'],
                            ['name' => 'GEORGES ST-PIERRE', 'style' => 'BALANCED', 'cartel' => '26-2'],
                            ['name' => 'BRAD TAVARES', 'style' => 'KICKBOXER', 'cartel' => '17-6'],
                            ['name' => 'DARREN TILL', 'style' => 'KICKBOXER', 'cartel' => '18-3-1'],
                            ['name' => 'CHRIS WEIDMAN', 'style' => 'WRESTLER', 'cartel' => '15-5'],
                            ['name' => 'ROBERT WHITTAKER', 'style' => 'BALANCED', 'cartel' => '21-5'],
                        ],
                        'LIGHT HEAVYWEIGHT' => [
                            ['name' => 'SAM ALVEY', 'style' => 'BOXER', 'cartel' => '33-14-0-1'],
                            ['name' => 'COREY ANDERSON', 'style' => 'WRESTLER', 'cartel' => '13-5'],
                            ['name' => 'VITOR BELFORT', 'style' => 'KICKBOXER', 'cartel' => '26-14-0-1'],
                            ['name' => 'JAN BLACHOWICZ', 'style' => 'BALANCED', 'cartel' => '26-8'],
                            ['name' => 'JARED CANNONIER', 'style' => 'KICKBOXER', 'cartel' => '13-4'],
                            ['name' => 'MISHA CIRKUNOV', 'style' => 'WRESTLER', 'cartel' => '15-5'],
                            ['name' => 'DANIEL CORMIER', 'style' => 'WRESTLER', 'cartel' => '22-3-0-1'],
                            ['name' => 'RASHAD EVANS', 'style' => 'WRESTLER', 'cartel' => '19-8-1'],
                            ['name' => 'FORREST GRIFFIN', 'style' => 'KICKBOXER', 'cartel' => '19-7'],
                            ['name' => 'ALEXANDER GUSTAFSSON', 'style' => 'KICKBOXER', 'cartel' => '18-7'],
                            ['name' => 'DAN HENDERSON', 'style' => 'BOXER', 'cartel' => '32-15'],
                            ['name' => 'RAMPAGE JACKSON', 'style' => 'BOXER', 'cartel' => '38-14'],
                            ['name' => 'ANTHONY JOHNSON', 'style' => 'KICKBOXER', 'cartel' => '22-6'],
                            ['name' => 'JON JONES', 'style' => 'KICKBOXER', 'cartel' => '26-1-0-1'],
                            ['name' => 'NIKITA KRYLOV', 'style' => 'KICKBOXER', 'cartel' => '27-7'],
                            ['name' => 'ILIR LATIFI', 'style' => 'BOXER', 'cartel' => '14-8-0-1'],
                            ['name' => 'CHUCK LIDDELL', 'style' => 'KICKBOXER', 'cartel' => '21-9'],
                            ['name' => 'LYOTO MACHIDA', 'style' => 'KICKBOXER', 'cartel' => '26-9'],
                            ['name' => 'JIMI MANUWA', 'style' => 'KICKBOXER', 'cartel' => '17-6'],
                            ['name' => 'MINOTOURO NOGUEIRA', 'style' => 'JIU-JITSU', 'cartel' => '23-10'],
                            ['name' => 'VOLKAN OEZDEMIR', 'style' => 'KICKBOXER', 'cartel' => '17-5'],
                            ['name' => 'TITO ORTIZ', 'style' => 'WRESTLER', 'cartel' => '21-12-1'],
                            ['name' => 'DOMINICK REYES', 'style' => 'KICKBOXER', 'cartel' => '12-1'],
                            ['name' => 'LUKE ROCKHOLD', 'style' => 'KICKBOXER', 'cartel' => '16-5'],
                            ['name' => 'SHOGUN RUA', 'style' => 'KICKBOXER', 'cartel' => '27-11-1'],
                            ['name' => 'OVINCE SAINT PREUX', 'style' => 'KICKBOXER', 'cartel' => '24-14'],
                            ['name' => 'GOKHAN SAKI', 'style' => 'KICKBOXER', 'cartel' => '1-2'],
                            ['name' => 'THIAGO SANTOS', 'style' => 'KICKBOXER', 'cartel' => '21-7'],
                            ['name' => 'ANDERSON SILVA', 'style' => 'KICKBOXER', 'cartel' => '34-10'],
                            ['name' => 'WANDERLEI SILVA', 'style' => 'BOXER', 'cartel' => '35-14-1-1'],
                            ['name' => 'ANTHONY SMITH', 'style' => 'BOXER', 'cartel' => '33-15'],
                            ['name' => 'JACARÉ SOUZA', 'style' => 'JIU-JITSU', 'cartel' => '26-8-0-1'],
                            ['name' => 'GLOVER TEIXEIRA', 'style' => 'BOXER', 'cartel' => '31-7'],
                            ['name' => 'GIAN VILLANTE', 'style' => 'KICKBOXER', 'cartel' => '17-12'],
                            ['name' => 'JOHNNY WALKER', 'style' => 'BOXER', 'cartel' => '17-5'],
                            ['name' => 'CHRIS WEIDMAN', 'style' => 'WRESTLER', 'cartel' => '15-5'],
                        ],
                        'HEAVYWEIGHT' => [
                            ['name' => 'ANDREI ARLOVSKI', 'style' => 'KICKBOXER', 'cartel' => '29-19-0-2'],
                            ['name' => 'CURTIS BLAYDES', 'style' => 'WRESTLER', 'cartel' => '14-2-0-1'],
                            ['name' => 'MARK COLEMAN', 'style' => 'WRESTLER', 'cartel' => '16-10'],
                            ['name' => 'DANIEL CORMIER', 'style' => 'WRESTLER', 'cartel' => '22-3-0-1'],
                            ['name' => 'JUNIOR DOS SANTOS', 'style' => 'KICKBOXER', 'cartel' => '21-8'],
                            ['name' => 'TODD DUFFEE', 'style' => 'BOXER', 'cartel' => '9-3-0-1'],
                            ['name' => 'WALT HARRIS', 'style' => 'WRESTLER', 'cartel' => '13-8-0-1'],
                            ['name' => 'ANTHONY JOHNSON', 'style' => 'KICKBOXER', 'cartel' => '22-6'],
                            ['name' => 'ILIR LATIFI', 'style' => 'BOXER', 'cartel' => '14-8-0-1'],
                            ['name' => 'DERRICK LEWIS', 'style' => 'BOXER', 'cartel' => '24-7-0-1'],
                            ['name' => 'STIPE MIOCIC', 'style' => 'BOXER', 'cartel' => '20-3'],
                            ['name' => 'FRANCIS NGANNOU', 'style' => 'BOXER', 'cartel' => '15-3'],
                            ['name' => 'MINOTAURO NOGUEIRA', 'style' => 'JIU-JITSU', 'cartel' => '34-10-1-1'],
                            ['name' => 'ALEKSEY OLEYNIK', 'style' => 'JIU-JITSU', 'cartel' => '59-14-1'],
                            ['name' => 'ALISTAIR OVEREEM', 'style' => 'KICKBOXER', 'cartel' => '46-18-0-1'],
                            ['name' => 'BEN ROTHWELL', 'style' => 'KICKBOXER', 'cartel' => '38-12'],
                            ['name' => 'JAIRZINHO ROZENSTRUIK', 'style' => 'KICKBOXER', 'cartel' => '11-1'],
                            ['name' => 'DAN SEVERN', 'style' => 'WRESTLER', 'cartel' => '101-19-7'],
                            ['name' => 'KIMBO SLICE', 'style' => 'BOXER', 'cartel' => '5-2-0-1'],
                            ['name' => 'STEFAN STRUVE', 'style' => 'KICKBOXER', 'cartel' => '29-12'],
                            ['name' => 'TAI TUIVASA', 'style' => 'BOXER', 'cartel' => '9-3'],
                            ['name' => 'CAIN VELASQUEZ', 'style' => 'WRESTLER', 'cartel' => '14-3'],
                            ['name' => 'ALEXANDER VOLKOV', 'style' => 'KICKBOXER', 'cartel' => '31-8'],
                            ['name' => 'FABRICIO WERDUM', 'style' => 'JIU-JITSU', 'cartel' => '24-9-1'],
                        ],
                    ]
                ];

        foreach($list as $genre => $item){
            foreach($item as $category => $fighters){
                foreach($fighters as $fighter){
                    try {
                        $obj = \App\Fighter::create($fighter);
                    }catch (\Illuminate\Database\QueryException $e){
                        $obj = \App\Fighter::where('name', $fighter['name'])->first();
                    }

                    $cat = \App\Category::where('description', $category)->where('genre', $genre)->first();
                    \App\CategoryFighter::create(['category_id' => $cat->id, 'fighter_id' => $obj->id]);
                }
            }
        }
    }
}
